### ISSUE TITLE
Segmentation Fault when updating device

### ISSUE THREAD

**Issue by rhassing** [syrhus/solax_inverter#3]
I'm sorry, but I have another issue.

2020-11-01 15:35:05.696 (Solax) Processing 'ReadEvent' message
2020-11-01 15:35:05.696 (Solax) Received 5 bytes of data
2020-11-01 15:35:05.696 (Solax) 30 0d 0a 0d 0a .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. 0....
2020-11-01 15:35:05.696 (Solax) Pushing 'onMessageCallback' on to queue
2020-11-01 15:35:05.696 (Solax) Processing 'onMessageCallback' message
2020-11-01 15:35:05.697 (Solax) Calling message handler 'onMessage'.
2020-11-01 15:35:05.697 (Solax) Current Inverter:1
2020-11-01 15:35:05.697 (Solax) uploadTime:2020-11-01 15:34:58
2020-11-01 15:35:05.698 (Solax) updateDevices called
2020-11-01 15:35:05.698 (Solax) nbInverters : 2
2020-11-01 15:35:05.698 (Solax) self.cumuls[0]= 3800
2020-11-01 15:35:05.698 (Solax) self.cumuls[2]= 3800
2020-11-01 15:35:05.698 (Solax) self.currents[0]= 76
2020-11-01 15:35:05.698 (Solax) self.currents[2]= 76
2020-11-01 15:35:05.698 (Solax) self.cumuls[1]= 1300
2020-11-01 15:35:05.698 (Solax) self.cumuls[2]= 5100
2020-11-01 15:35:05.699 (Solax) self.currents[1]= 5
2020-11-01 15:35:05.699 (Solax) self.currents[2]= 81
2020-11-01 15:35:05.699 (Solax) updateDevice called 1
2020-11-01 15:35:05.699 (Solax) strValue :76;3800
2020-11-01 15:35:05.699 (Solax - XXXXXXXXXXX) Updating device from 0:'' to have values 0:'76;3800'.
2020-11-01 15:35:05.701 Error: Domoticz(pid:4042, tid:4048('PluginMgr')) received fatal signal 11 (Segmentation fault)
2020-11-01 15:35:05.701 Error: siginfo address=0xfca, address=(nil)

**Comment by alexandreburza** [comment]
merci rageur même problème
Alexandre

**Comment by syrhus** [comment]
The error seems to come from "PluginMgr". Is it possible to disable it just to test? I don't installed Plugin Manager so I don't have the error.

**Comment by syrhus** [comment]
> I'm sorry, but I have another issue.
> 
> 2020-11-01 15:35:05.696 (Solax) Processing 'ReadEvent' message
> 2020-11-01 15:35:05.696 (Solax) Received 5 bytes of data
> 2020-11-01 15:35:05.696 (Solax) 30 0d 0a 0d 0a .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. 0....
> 2020-11-01 15:35:05.696 (Solax) Pushing 'onMessageCallback' on to queue
> 2020-11-01 15:35:05.696 (Solax) Processing 'onMessageCallback' message
> 2020-11-01 15:35:05.697 (Solax) Calling message handler 'onMessage'.
> 2020-11-01 15:35:05.697 (Solax) Current Inverter:1
> 2020-11-01 15:35:05.697 (Solax) uploadTime:2020-11-01 15:34:58
> 2020-11-01 15:35:05.698 (Solax) updateDevices called
> 2020-11-01 15:35:05.698 (Solax) nbInverters : 2
> 2020-11-01 15:35:05.698 (Solax) self.cumuls[0]= 3800
> 2020-11-01 15:35:05.698 (Solax) self.cumuls[2]= 3800
> 2020-11-01 15:35:05.698 (Solax) self.currents[0]= 76
> 2020-11-01 15:35:05.698 (Solax) self.currents[2]= 76
> 2020-11-01 15:35:05.698 (Solax) self.cumuls[1]= 1300
> 2020-11-01 15:35:05.698 (Solax) self.cumuls[2]= 5100
> 2020-11-01 15:35:05.699 (Solax) self.currents[1]= 5
> 2020-11-01 15:35:05.699 (Solax) self.currents[2]= 81
> 2020-11-01 15:35:05.699 (Solax) updateDevice called 1
> 2020-11-01 15:35:05.699 (Solax) strValue :76;3800
**> 2020-11-01 15:35:05.699 (Solax - XXXXXXXXXXX) Updating device from 0:'' to have values 0:'76;3800'.**
> 2020-11-01 15:35:05.701 Error: Domoticz(pid:4042, tid:4048('PluginMgr')) received fatal signal 11 (Segmentation fault)
> 2020-11-01 15:35:05.701 Error: siginfo address=0xfca, address=(nil)

The bold line is very strange! You should have :
**> 2020-11-01 15:35:05.699 (Solax - XXXXXXXXXXX) Updating device from 0:'76;3800'.**
instead
I don't understand what is the "to have values 0" . Do you have an idea? Could you look at your code file to check it please?
The line 281 should be:
`Domoticz.Log("Update 0:'"+ strValue +"' ("+Devices[Unit].Name+")")`

**Comment by rhassing** [comment]
Line 281 is:
                Domoticz.Log("Update 0:'"+ strValue +"' ("+Devices[Unit].Name+")")

In the bold line I changed the Serialnumber with the X's to not reveal the serialnumber on the internet.

**Comment by syrhus** [comment]
I understood that you have masked the serial number but I really don't understand what is the "to have values" text inside the debug output.
It looks like a memory allocation issue between differents plugins.
Have you try to disable the PluginManager?

**Comment by rhassing** [comment]
I'm not sure how to disable the plug-in manager. Is it in the settings, the auto update?

**Comment by rhassing** [comment]
I have some additional logging:

2020-11-03 11:11:30.119  (Solax) Pushing 'onHeartbeatCallback' on to queue
2020-11-03 11:11:30.134  (Solax) Processing 'onHeartbeatCallback' message
2020-11-03 11:11:30.134  (Solax) Calling message handler 'onHeartbeat'.
2020-11-03 11:11:30.134  (Solax) onHeartbeat called
2020-11-03 11:11:30.134  (Solax) now: 2020-11-03
2020-11-03 11:11:30.134  (Solax) currentDate:2020-11-03
2020-11-03 11:11:30.135  Status: (Solax) On
2020-11-03 11:11:30.135  (Solax) Pushing 'ProtocolDirective' on to queue
2020-11-03 11:11:30.135  (Solax) Pushing 'ConnectDirective' on to queue
2020-11-03 11:11:30.135  (Solax) Processing 'ProtocolDirective' message
2020-11-03 11:11:30.135  (Solax) Protocol set to: 'HTTPS'.
2020-11-03 11:11:30.135  (Solax) Processing 'ConnectDirective' message
2020-11-03 11:11:30.135  (Solax) Transport set to: 'TCP/IP', www.eu.solaxcloud.com:9443.
2020-11-03 11:11:30.157  (Solax) Connect directive received, action initiated successfully.
2020-11-03 11:11:30.745  (Solax) Pushing 'onConnectCallback' on to queue
2020-11-03 11:11:30.758  (Solax) Processing 'onConnectCallback' message
2020-11-03 11:11:30.759  (Solax) Calling message handler 'onConnect'.
2020-11-03 11:11:30.759  (Solax) Status:0
2020-11-03 11:11:30.759  (Solax) Current Inverter:0
2020-11-03 11:11:30.759  (Solax) Pushing 'WriteDirective' on to queue
2020-11-03 11:11:30.760  (Solax) Processing 'WriteDirective' message
2020-11-03 11:11:30.760  (Solax) Sending 209 bytes of data
2020-11-03 11:11:30.760  (Solax)     47 45 54 20 2f 70 72 6f 78 79 2f 61 70 69 2f 67 65 74 52 65     GET./proxy/api/getRe
2020-11-03 11:11:30.760  (Solax)     61 6c 74 69 6d 65 49 6e 66 6f 2e 64 6f 3f 74 6f 6b 65 6e 49     altimeInfo.do?tokenI
2020-11-03 11:11:30.760  (Solax)     64 3d 32 30 32 30 31 30 33 31 32 30 32 34 32 34 39 34 30 35     d=2XXXXXXXXXX
2020-11-03 11:11:30.760  (Solax)     33 37 37 35 39 26 73 6e 3d 53 57 57 4c 36 39 46 47 58 4c 20     37759&sn=XXXXXXXXXXX.
2020-11-03 11:11:30.760  (Solax)     48 54 54 50 2f 31 2e 31 0d 0a 55 73 65 72 2d 41 67 65 6e 74     HTTP/1.1..User-Agent
2020-11-03 11:11:30.761  (Solax)     3a 20 44 6f 6d 6f 74 69 63 7a 2f 31 2e 30 0d 0a 41 63 63 65     :.Domoticz/1.0..Acce
2020-11-03 11:11:30.761  (Solax)     70 74 3a 20 61 70 70 6c 69 63 61 74 69 6f 6e 2f 6a 73 6f 6e     pt:.application/json
2020-11-03 11:11:30.761  (Solax)     0d 0a 43 6f 6e 74 65 6e 74 2d 54 79 70 65 3a 20 61 70 70 6c     ..Content-Type:.appl
2020-11-03 11:11:30.761  (Solax)     69 63 61 74 69 6f 6e 2f 6a 73 6f 6e 0d 0a 48 6f 73 74 3a 20     ication/json..Host:.
2020-11-03 11:11:30.761  (Solax)     77 77 77 2e 65 75 2e 73 6f 6c 61 78 63 6c 6f 75 64 2e 63 6f     www.eu.solaxcloud.co
2020-11-03 11:11:30.761  (Solax)     6d 39 34 34 33 0d 0a 0d 0a .. .. .. .. .. .. .. .. .. .. ..     m9443....
2020-11-03 11:11:30.792  (Solax) Pushing 'ReadEvent' on to queue
2020-11-03 11:11:30.795  (Solax) Pushing 'ReadEvent' on to queue
2020-11-03 11:11:30.812  (Solax) Processing 'ReadEvent' message
2020-11-03 11:11:30.813  (Solax) Received 586 bytes of data
2020-11-03 11:11:30.813  (Solax)     48 54 54 50 2f 31 2e 31 20 32 30 30 20 4f 4b 0d 0a 53 65 72     HTTP/1.1.200.OK..Ser
2020-11-03 11:11:30.813  (Solax)     76 65 72 3a 20 41 70 61 63 68 65 2d 43 6f 79 6f 74 65 2f 31     ver:.Apache-Coyote/1
2020-11-03 11:11:30.813  (Solax)     2e 31 0d 0a 41 63 63 65 73 73 2d 43 6f 6e 74 72 6f 6c 2d 41     .1..Access-Control-A
2020-11-03 11:11:30.813  (Solax)     6c 6c 6f 77 2d 4f 72 69 67 69 6e 3a 20 2a 0d 0a 41 63 63 65     llow-Origin:.*..Acce
2020-11-03 11:11:30.813  (Solax)     73 73 2d 43 6f 6e 74 72 6f 6c 2d 41 6c 6c 6f 77 2d 48 65 61     ss-Control-Allow-Hea
2020-11-03 11:11:30.813  (Solax)     64 65 72 73 3a 20 41 75 74 68 65 6e 74 69 63 61 74 69 6f 6e     ders:.Authentication
2020-11-03 11:11:30.814  (Solax)     0d 0a 43 6f 6e 74 65 6e 74 2d 54 79 70 65 3a 20 61 70 70 6c     ..Content-Type:.appl
2020-11-03 11:11:30.814  (Solax)     69 63 61 74 69 6f 6e 2f 6a 73 6f 6e 0d 0a 54 72 61 6e 73 66     ication/json..Transf
2020-11-03 11:11:30.814  (Solax)     65 72 2d 45 6e 63 6f 64 69 6e 67 3a 20 63 68 75 6e 6b 65 64     er-Encoding:.chunked
2020-11-03 11:11:30.814  (Solax)     0d 0a 44 61 74 65 3a 20 54 75 65 2c 20 30 33 20 4e 6f 76 20     ..Date:.Tue,.03.Nov.
2020-11-03 11:11:30.814  (Solax)     32 30 32 30 20 31 30 3a 31 31 3a 33 30 20 47 4d 54 0d 0a 0d     2020.10:11:30.GMT...
2020-11-03 11:11:30.814  (Solax)     0a 31 36 36 0d 0a 7b 22 65 78 63 65 70 74 69 6f 6e 22 3a 22     .166..{"exception":"
2020-11-03 11:11:30.814  (Solax)     51 75 65 72 79 20 73 75 63 63 65 73 73 21 22 2c 22 72 65 73     Query.success!","res
2020-11-03 11:11:30.814  (Solax)     75 6c 74 22 3a 7b 22 69 6e 76 65 72 74 65 72 53 4e 22 3a 22     ult":{"inverterSN":"
2020-11-03 11:11:30.814  (Solax)     58 41 47 33 30 32 46 34 30 37 37 30 39 38 22 2c 22 73 6e 22     XXXXXXXXXXXX","sn"
2020-11-03 11:11:30.815  (Solax)     3a 22 53 57 57 4c 36 39 46 47 58 4c 22 2c 22 61 63 70 6f 77     :"XXXXXXXXXXX","acpow
2020-11-03 11:11:30.815  (Solax)     65 72 22 3a 31 36 37 31 2e 30 2c 22 79 69 65 6c 64 74 6f 64     er":1671.0,"yieldtod
2020-11-03 11:11:30.815  (Solax)     61 79 22 3a 34 2e 31 2c 22 79 69 65 6c 64 74 6f 74 61 6c 22     ay":4.1,"yieldtotal"
2020-11-03 11:11:30.815  (Solax)     3a 34 36 35 34 2e 39 2c 22 66 65 65 64 69 6e 70 6f 77 65 72     :4654.9,"feedinpower
2020-11-03 11:11:30.815  (Solax)     22 3a 30 2e 30 2c 22 66 65 65 64 69 6e 65 6e 65 72 67 79 22     ":0.0,"feedinenergy"
2020-11-03 11:11:30.815  (Solax)     3a 30 2e 30 2c 22 63 6f 6e 73 75 6d 65 65 6e 65 72 67 79 22     :0.0,"consumeenergy"
2020-11-03 11:11:30.815  (Solax)     3a 30 2e 30 2c 22 66 65 65 64 69 6e 70 6f 77 65 72 4d 32 22     :0.0,"feedinpowerM2"
2020-11-03 11:11:30.815  (Solax)     3a 30 2e 30 2c 22 73 6f 63 22 3a 30 2e 30 2c 22 70 65 70 73     :0.0,"soc":0.0,"peps
2020-11-03 11:11:30.816  (Solax)     31 22 3a 30 2e 30 2c 22 70 65 70 73 32 22 3a 30 2e 30 2c 22     1":0.0,"peps2":0.0,"
2020-11-03 11:11:30.816  (Solax)     70 65 70 73 33 22 3a 30 2e 30 2c 22 69 6e 76 65 72 74 65 72     peps3":0.0,"inverter
2020-11-03 11:11:30.816  (Solax)     54 79 70 65 22 3a 22 34 22 2c 22 69 6e 76 65 72 74 65 72 53     Type":"4","inverterS
2020-11-03 11:11:30.816  (Solax)     74 61 74 75 73 22 3a 22 31 30 32 22 2c 22 75 70 6c 6f 61 64     tatus":"102","upload
2020-11-03 11:11:30.816  (Solax)     54 69 6d 65 22 3a 22 32 30 32 30 2d 31 31 2d 30 33 20 31 31     Time":"2020-11-03.11
2020-11-03 11:11:30.816  (Solax)     3a 31 31 3a 30 38 22 7d 2c 22 73 75 63 63 65 73 73 22 3a 74     :11:08"},"success":t
2020-11-03 11:11:30.816  (Solax)     72 75 65 7d 0d 0a .. .. .. .. .. .. .. .. .. .. .. .. .. ..     rue}..
2020-11-03 11:11:30.817  (Solax) Processing 'ReadEvent' message
2020-11-03 11:11:30.817  (Solax) Received 5 bytes of data
2020-11-03 11:11:30.817  (Solax)     30 0d 0a 0d 0a .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     0....
2020-11-03 11:11:30.817  (Solax) Pushing 'onMessageCallback' on to queue
2020-11-03 11:11:30.817  (Solax) Processing 'onMessageCallback' message
2020-11-03 11:11:30.817  (Solax) Calling message handler 'onMessage'.
2020-11-03 11:11:30.818  (Solax) Current Inverter:0
2020-11-03 11:11:30.819  (Solax) uploadTime:2020-11-03 11:11:08
2020-11-03 11:11:30.819  (Solax) Load next inverter:1
2020-11-03 11:11:30.819  (Solax) Current Inverter:1
2020-11-03 11:11:30.819  (Solax) Pushing 'WriteDirective' on to queue
2020-11-03 11:11:30.820  (Solax) Processing 'WriteDirective' message
2020-11-03 11:11:30.820  (Solax) Sending 209 bytes of data
2020-11-03 11:11:30.820  (Solax)     47 45 54 20 2f 70 72 6f 78 79 2f 61 70 69 2f 67 65 74 52 65     GET./proxy/api/getRe
2020-11-03 11:11:30.820  (Solax)     61 6c 74 69 6d 65 49 6e 66 6f 2e 64 6f 3f 74 6f 6b 65 6e 49     altimeInfo.do?tokenI
2020-11-03 11:11:30.820  (Solax)     64 3d 32 30 32 30 31 30 33 31 32 30 32 34 32 34 39 34 30 35     d=XXXXXXXXXXXXXXX
2020-11-03 11:11:30.820  (Solax)     33 37 37 35 39 26 73 6e 3d 53 57 53 37 4b 54 56 4a 4b 4a 20     37759&sn=XXXXXXXXX.
2020-11-03 11:11:30.820  (Solax)     48 54 54 50 2f 31 2e 31 0d 0a 55 73 65 72 2d 41 67 65 6e 74     HTTP/1.1..User-Agent
2020-11-03 11:11:30.821  (Solax)     3a 20 44 6f 6d 6f 74 69 63 7a 2f 31 2e 30 0d 0a 41 63 63 65     :.Domoticz/1.0..Acce
2020-11-03 11:11:30.821  (Solax)     70 74 3a 20 61 70 70 6c 69 63 61 74 69 6f 6e 2f 6a 73 6f 6e     pt:.application/json
2020-11-03 11:11:30.821  (Solax)     0d 0a 43 6f 6e 74 65 6e 74 2d 54 79 70 65 3a 20 61 70 70 6c     ..Content-Type:.appl
2020-11-03 11:11:30.821  (Solax)     69 63 61 74 69 6f 6e 2f 6a 73 6f 6e 0d 0a 48 6f 73 74 3a 20     ication/json..Host:.
2020-11-03 11:11:30.821  (Solax)     77 77 77 2e 65 75 2e 73 6f 6c 61 78 63 6c 6f 75 64 2e 63 6f     www.eu.solaxcloud.co
2020-11-03 11:11:30.821  (Solax)     6d 39 34 34 33 0d 0a 0d 0a .. .. .. .. .. .. .. .. .. .. ..     m9443....
2020-11-03 11:11:30.859  (Solax) Pushing 'ReadEvent' on to queue
2020-11-03 11:11:30.864  (Solax) Pushing 'ReadEvent' on to queue
2020-11-03 11:11:30.872  (Solax) Processing 'ReadEvent' message
2020-11-03 11:11:30.872  (Solax) Received 584 bytes of data
2020-11-03 11:11:30.872  (Solax)     48 54 54 50 2f 31 2e 31 20 32 30 30 20 4f 4b 0d 0a 53 65 72     HTTP/1.1.200.OK..Ser
2020-11-03 11:11:30.872  (Solax)     76 65 72 3a 20 41 70 61 63 68 65 2d 43 6f 79 6f 74 65 2f 31     ver:.Apache-Coyote/1
2020-11-03 11:11:30.873  (Solax)     2e 31 0d 0a 41 63 63 65 73 73 2d 43 6f 6e 74 72 6f 6c 2d 41     .1..Access-Control-A
2020-11-03 11:11:30.873  (Solax)     6c 6c 6f 77 2d 4f 72 69 67 69 6e 3a 20 2a 0d 0a 41 63 63 65     llow-Origin:.*..Acce
2020-11-03 11:11:30.873  (Solax)     73 73 2d 43 6f 6e 74 72 6f 6c 2d 41 6c 6c 6f 77 2d 48 65 61     ss-Control-Allow-Hea
2020-11-03 11:11:30.873  (Solax)     64 65 72 73 3a 20 41 75 74 68 65 6e 74 69 63 61 74 69 6f 6e     ders:.Authentication
2020-11-03 11:11:30.873  (Solax)     0d 0a 43 6f 6e 74 65 6e 74 2d 54 79 70 65 3a 20 61 70 70 6c     ..Content-Type:.appl
2020-11-03 11:11:30.873  (Solax)     69 63 61 74 69 6f 6e 2f 6a 73 6f 6e 0d 0a 54 72 61 6e 73 66     ication/json..Transf
2020-11-03 11:11:30.873  (Solax)     65 72 2d 45 6e 63 6f 64 69 6e 67 3a 20 63 68 75 6e 6b 65 64     er-Encoding:.chunked
2020-11-03 11:11:30.874  (Solax)     0d 0a 44 61 74 65 3a 20 54 75 65 2c 20 30 33 20 4e 6f 76 20     ..Date:.Tue,.03.Nov.
2020-11-03 11:11:30.874  (Solax)     32 30 32 30 20 31 30 3a 31 31 3a 33 30 20 47 4d 54 0d 0a 0d     2020.10:11:30.GMT...
2020-11-03 11:11:30.874  (Solax)     0a 31 36 34 0d 0a 7b 22 65 78 63 65 70 74 69 6f 6e 22 3a 22     .164..{"exception":"
2020-11-03 11:11:30.874  (Solax)     51 75 65 72 79 20 73 75 63 63 65 73 73 21 22 2c 22 72 65 73     Query.success!","res
2020-11-03 11:11:30.874  (Solax)     75 6c 74 22 3a 7b 22 69 6e 76 65 72 74 65 72 53 4e 22 3a 22     ult":{"inverterSN":"
2020-11-03 11:11:30.874  (Solax)     58 4d 54 32 30 32 47 34 30 34 30 30 33 37 22 2c 22 73 6e 22     XXXXXXXXXXXX7","sn"
2020-11-03 11:11:30.874  (Solax)     3a 22 53 57 53 37 4b 54 56 4a 4b 4a 22 2c 22 61 63 70 6f 77     :"XXXXXXXXXX","acpow
2020-11-03 11:11:30.875  (Solax)     65 72 22 3a 31 34 33 2e 30 2c 22 79 69 65 6c 64 74 6f 64 61     er":143.0,"yieldtoda
2020-11-03 11:11:30.875  (Solax)     79 22 3a 30 2e 32 2c 22 79 69 65 6c 64 74 6f 74 61 6c 22 3a     y":0.2,"yieldtotal":
2020-11-03 11:11:30.875  (Solax)     32 30 39 2e 33 2c 22 66 65 65 64 69 6e 70 6f 77 65 72 22 3a     209.3,"feedinpower":
2020-11-03 11:11:30.875  (Solax)     30 2e 30 2c 22 66 65 65 64 69 6e 65 6e 65 72 67 79 22 3a 30     0.0,"feedinenergy":0
2020-11-03 11:11:30.875  (Solax)     2e 30 2c 22 63 6f 6e 73 75 6d 65 65 6e 65 72 67 79 22 3a 30     .0,"consumeenergy":0
2020-11-03 11:11:30.875  (Solax)     2e 30 2c 22 66 65 65 64 69 6e 70 6f 77 65 72 4d 32 22 3a 30     .0,"feedinpowerM2":0
2020-11-03 11:11:30.875  (Solax)     2e 30 2c 22 73 6f 63 22 3a 30 2e 30 2c 22 70 65 70 73 31 22     .0,"soc":0.0,"peps1"
2020-11-03 11:11:30.876  (Solax)     3a 30 2e 30 2c 22 70 65 70 73 32 22 3a 30 2e 30 2c 22 70 65     :0.0,"peps2":0.0,"pe
2020-11-03 11:11:30.876  (Solax)     70 73 33 22 3a 30 2e 30 2c 22 69 6e 76 65 72 74 65 72 54 79     ps3":0.0,"inverterTy
2020-11-03 11:11:30.876  (Solax)     70 65 22 3a 22 34 22 2c 22 69 6e 76 65 72 74 65 72 53 74 61     pe":"4","inverterSta
2020-11-03 11:11:30.876  (Solax)     74 75 73 22 3a 22 31 30 32 22 2c 22 75 70 6c 6f 61 64 54 69     tus":"102","uploadTi
2020-11-03 11:11:30.876  (Solax)     6d 65 22 3a 22 32 30 32 30 2d 31 31 2d 30 33 20 31 31 3a 31     me":"2020-11-03.11:1
2020-11-03 11:11:30.876  (Solax)     31 3a 32 38 22 7d 2c 22 73 75 63 63 65 73 73 22 3a 74 72 75     1:28"},"success":tru
2020-11-03 11:11:30.876  (Solax)     65 7d 0d 0a .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     e}..
2020-11-03 11:11:30.877  (Solax) Processing 'ReadEvent' message
2020-11-03 11:11:30.877  (Solax) Received 5 bytes of data
2020-11-03 11:11:30.877  (Solax)     30 0d 0a 0d 0a .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     0....
2020-11-03 11:11:30.877  (Solax) Pushing 'onMessageCallback' on to queue
2020-11-03 11:11:30.877  (Solax) Processing 'onMessageCallback' message
2020-11-03 11:11:30.877  (Solax) Calling message handler 'onMessage'.
2020-11-03 11:11:30.878  (Solax) Current Inverter:1
2020-11-03 11:11:30.879  (Solax) uploadTime:2020-11-03 11:11:28
2020-11-03 11:11:30.879  (Solax) updateDevices called
2020-11-03 11:11:30.879  (Solax) nbInverters : 2
2020-11-03 11:11:30.879  (Solax) self.cumuls[0]= 4100
2020-11-03 11:11:30.879  (Solax) self.cumuls[2]= 4100
2020-11-03 11:11:30.880  (Solax) self.currents[0]= 1671
2020-11-03 11:11:30.880  (Solax) self.currents[2]= 1671
2020-11-03 11:11:30.880  (Solax) self.cumuls[1]= 200
2020-11-03 11:11:30.880  (Solax) self.cumuls[2]= 4300
2020-11-03 11:11:30.880  (Solax) self.currents[1]= 143
2020-11-03 11:11:30.880  (Solax) self.currents[2]= 1814
2020-11-03 11:11:30.881  (Solax) updateDevice called 1
2020-11-03 11:11:30.881  (Solax) strValue :1671;4100
2020-11-03 11:11:30.881  (Solax - XXXXXXXXXXX) Updating device from 0:'' to have values 0:'1671;4100'.
2020-11-03 11:11:30.883  Error: Domoticz(pid:3919, tid:3922('PluginMgr')) received fatal signal 11 (Segmentation fault)
2020-11-03 11:11:30.883  Error: siginfo address=0xf4f, address=(nil)
2020-11-03 11:11:38.094  Error: Thread 4 (Thread 0x74af7220 (LWP 3922)):
2020-11-03 11:11:38.095  Error: #0  __waitpid (options=0, stat_loc=0x74af51f0, pid=4002) at ../sysdeps/unix/sysv/linux/waitpid.c:30
2020-11-03 11:11:38.095  Error: #1  __waitpid (pid=4002, stat_loc=0x74af51f0, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:25
2020-11-03 11:11:38.095  Error: #2  0x002db8ec in dumpstack_gdb(bool) ()
2020-11-03 11:11:38.095  Error: #3  0x002dbeb8 in signal_handler(int, siginfo_t*, void*) ()
2020-11-03 11:11:38.095  Error: #4  <signal handler called>
2020-11-03 11:11:38.095  Error: #5  raise (sig=11) at ../sysdeps/unix/sysv/linux/raise.c:50
2020-11-03 11:11:38.095  Error: #6  <signal handler called>
2020-11-03 11:11:38.096  Error: #7  0x0030f080 in CSQLHelper::UpdateValueInt(int, char const*, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool) ()
2020-11-03 11:11:38.096  Error: #8  0x74af6390 in ?? ()

**Comment by syrhus** [comment]
Hi
I really don't understand this issue. Following my log:

2020-11-03 11:56:24.475 (Onduleurs) updateDevice called 1
2020-11-03 11:56:24.475 (Onduleurs) strValue :371;1200
2020-11-03 11:56:24.476 (Onduleurs - Maison) Updating device from 0:'457;1100' to have values 0:'371;1200'.
2020-11-03 11:56:24.498 (Onduleurs) Update 0:'371;1200' (Onduleurs - Maison)
2020-11-03 11:56:24.499 (Onduleurs) updateDevice called 2
2020-11-03 11:56:24.499 (Onduleurs) strValue :287;600
2020-11-03 11:56:24.499 (Onduleurs - Garage) Updating device from 0:'332;600' to have values 0:'287;600'.
2020-11-03 11:56:24.521 (Onduleurs) Update 0:'287;600' (Onduleurs - Garage)
2020-11-03 11:56:24.521 (Onduleurs) updateDevice called 3
2020-11-03 11:56:24.521 (Onduleurs) strValue :658;1800
2020-11-03 11:56:24.521 (Onduleurs - Total) Updating device from 0:'789;1700' to have values 0:'658;1800'.
2020-11-03 11:56:24.539 (Onduleurs) Update 0:'658;1800' (Onduleurs - Total)

It seems that the previous value cannot be fetched.
could you edit your devices and check if you have the same parameters like following screen-capture?
![onduleurs-garage](https://user-images.githubusercontent.com/34164789/97977520-9e38f980-1dcc-11eb-8107-22cc7c576650.png)

**Comment by rhassing** [comment]
The type is not filled in. I changed that to Return now.
That seemed to be the problem. It's working now.
Thank you very much for your help.

**Comment by syrhus** [comment]
I've changed the code to create device with the good parameters :
- Type => Return 
- Energy read => From device
